# Generated by Django 5.2.5 on 2025-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('seller', 'Seller'), ('trade_in', 'Trade-In'), ('buyer', 'Buyer')], max_length=20)),
                ('status', models.CharField(choices=[('deal', 'Deal'), ('negotiating', 'Negotiating'), ('not_deal', 'Not Deal'), ('uncontacted', 'Uncontacted'), ('rna', 'RNA (Return, No Answer)')], default='uncontacted', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('merek', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('tahun', models.IntegerField(max_length=4)),
                ('transmisi', models.CharField(choices=[('auto', 'Otomatis'), ('manual', 'Manual')], max_length=20)),
                ('varian', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kilometer', models.IntegerField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
