# Generated by Django 5.2.5 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kilometer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tahun',
            field=models.IntegerField(),
        ),
    ]
