# Generated by Django 5.2.5 on 2025-09-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_kilometer_alter_customer_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='kilometer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='merek',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='model',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='transmisi',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='varian',
        ),
    ]
