# Generated by Django 5.2.5 on 2025-09-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_kilometer_remove_customer_merek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
    ]
