# Generated by Django 5.2.5 on 2025-09-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('customer', '0004_remove_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='cars.cars'),
        ),
    ]
