# Generated by Django 5.2.5 on 2025-09-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_car_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car_wishlist',
        ),
    ]
