# Generated by Django 5.2.5 on 2025-09-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('booked', 'Booked')], default='available', max_length=20),
        ),
    ]
