# Generated by Django 5.2.5 on 2025-12-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.cars')),
            ],
        ),
    ]
