# Generated by Django 5.2.5 on 2025-09-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('customer', '0003_remove_customer_kilometer_remove_customer_merek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('sell', 'Sell'), ('trade', 'Trade'), ('buy', 'Buy')], max_length=10)),
                ('offered_vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('offered_vehicle_varian', models.CharField(blank=True, max_length=100, null=True)),
                ('offered_vehicle_transmission', models.CharField(choices=[('auto', 'Otomatis'), ('manual', 'Manual')], max_length=20)),
                ('offered_vehicle_province', models.CharField(blank=True, max_length=50, null=True)),
                ('offered_vehicle_year', models.IntegerField(blank=True, null=True)),
                ('offered_vehicle_kilometers', models.IntegerField(blank=True, null=True)),
                ('offered_vehicle_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('showroom_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
            ],
        ),
    ]
