# Generated by Django 5.2.5 on 2025-09-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_car_wishlist'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_kilometers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_province',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_transmission',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_varian',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offered_vehicle_year',
        ),
        migrations.CreateModel(
            name='TradeInCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('offered_vehicle_varian', models.CharField(blank=True, max_length=100, null=True)),
                ('offered_vehicle_transmission', models.CharField(choices=[('auto', 'Otomatis'), ('manual', 'Manual')], max_length=20)),
                ('offered_vehicle_province', models.CharField(blank=True, max_length=50, null=True)),
                ('offered_vehicle_year', models.IntegerField(blank=True, null=True)),
                ('offered_vehicle_kilometers', models.IntegerField(blank=True, null=True)),
                ('offered_vehicle_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trade_in_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tradeincar'),
        ),
    ]
