# Generated by Django 5.2.5 on 2025-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_offered_vehicle_kilometers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeincar',
            name='offered_vehicle_transmission',
            field=models.CharField(blank=True, choices=[('auto', 'Otomatis'), ('manual', 'Manual')], max_length=20, null=True),
        ),
    ]
